#!/bin/bash

# TigerOS script for the removal of unwanted major-specific packages
# Author: Tim Zabel <tjz8659@rit.edu>

# Check to see if the current user is root
if [ $EUID != 0 ]
then
    echo "Please run this script as root (sudo $@$0)."
    exit
fi

echo -e "Welcome to the TigerOS package removal script.\n
This script will remove all files and packages installed for a specific major."
echo -e "\n"
sleep 5;

PS3='Please enter the major for the courses you wish to remove: '
options=("CS" "IT/WMC" "NSSA/CIT" "SE" "Quit")
select opt in "${options[@]}"
do
    # all dnf commands here are done with the -y flag. Individual removals do not ask the user for permission beforehand
    case $opt in
        "CS")
            echo -e "Welcome to the TigerOS CS package removal script.\n
                  This script will remove Intellij idea, PyCharm, prolog, racket, and JFLAP from your machine."
            while true; do
                read -p "Do you wish to continue? [y/n] " yn
                case $yn in
                    [Yy]* ) break;;
                    [Nn]* ) exit;;
                esac
            done
            ./cs/idea.sh --remove       # removes Intellij IDEA
            ./cs/logisim.sh --remove    # removes logisim
            ./cs/jflap.sh --remove      # removes JFLAP
            ;;
        "IT/WMC")
            echo -e "Welcome to the TigerOS IT/WMC package removal script.\n
            This script will remove mysql, mongodb, subversion, filezilla, and nodejs from your machine."
            while true; do
                read -p "Do you wish to continue? [y/n] " yn
                case $yn in
                    [Yy]* ) break;;
                    [Nn]* ) exit;;
                esac
            done
            sudo dnf -y remove mongodb subversion filezilla nodejs php mysql-repo.rpm mysql-community-server
			semanage port -d -t mongod_port_t -p tcp 27017
			firewall-cmd --del-port=22017/tcp --permanent && firewall-cmd --reload
            # jGrasp installer script must be implemented before it can be removed.
            ;;
        "NSSA/CIT")
            echo -e "Welcome to the TigerOS NSSA/CIT package removal script.\n
                  This script will remove wireshark, python 2.7, python 3, and jGrasp from your machine."
            while true; do
                read -p "Do you wish to continue [y/n] " yn
                case $yn in
                    [Yy]* ) break;;
                    [Nn]* ) exit;;
                esac
            done
            sudo dnf -y remove wireshark
            # WARNING --> jGrasp has not been implemented in the installer script yet. Cannot remove
            echo "Install finished."
            exit
            ;;
        "SE" )
            echo -e "Welcome to the TigerOS Software Engineering removal script.\n
                  This script will remove ruby, eclipse, Spin, sqlite3 and MIT Alloy from your machine."
            while true; do
                read -p "Do you wish to continue? [y/n] " yn
                case $yn in
                    [Yy]* ) break;;
                    [Nn]* ) exit;;
                esac
            done
            sudo dnf -y remove eclipse-jdt ruby sqlite gitk plantuml
            ./se/spin.sh --remove       
			./se/alloy.sh --remove    
            echo "All files have been removed."
            exit
            ;;
        "Quit")
            break
            ;;
        *)
            echo "Invalid Option."
            ;;
    esac
done
